# Autism Prediction on Adults

Data Exploration

In [1]:
# For adult dataset
import arff
import pandas as pd
# Load arff file
with open('Autism-Adult-Data.arff') as f:
    dataset = arff.load(f)
# Convert to DataFrame
adult = pd.DataFrame(dataset['data'], columns=[attr[0] for attr in dataset['attributes']])
# Display 
adult

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,United States,no,6.0,18 and more,Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5.0,18 and more,Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8.0,18 and more,Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,United States,no,6.0,18 and more,Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,None,no,no,Egypt,no,2.0,18 and more,None,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7.0,18 and more,Self,YES
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3.0,18 and more,Parent,NO
701,1,0,1,1,1,0,1,1,0,1,...,f,None,no,no,Russia,no,7.0,18 and more,None,YES
702,1,0,0,1,1,0,1,0,1,1,...,m,South Asian,no,no,Pakistan,no,6.0,18 and more,Self,NO
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8.0,18 and more,Self,YES

In [2]:
# To know the number of rows and columns in a dataframe
adult.shape

(704, 21)

In [3]:
# To display all the columns
pd.set_option('display.max_columns',None)

In [4]:
# The dataset contains data like ? and I am replacing those values with null by using numpy library
import numpy as np
adult = adult.replace('?', np.nan)

In [5]:
# To know how many null values present in the dataset and the datatype of each column
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   A1_Score         704 non-null    object
 1   A2_Score         704 non-null    object
 2   A3_Score         704 non-null    object
 3   A4_Score         704 non-null    object
 4   A5_Score         704 non-null    object
 5   A6_Score         704 non-null    object
 6   A7_Score         704 non-null    object
 7   A8_Score         704 non-null    object
 8   A9_Score         704 non-null    object
 9   A10_Score        704 non-null    object
 10  age              702 non-null    float64
 11  gender           704 non-null    object
 12  ethnicity        609 non-null    object
 13  jundice          704 non-null    object
 14  austim           704 non-null    object
 15  contry_of_res    704 non-null    object
 16  used_app_before  704 non-null    object
 17  result           704 non-null    float64
 18  age_desc         704 non-null    object
 19  relation         609 non-null    object
 20  Class/ASD        704 non-null    object
dtypes: float64(2), object(19)
memory usage: 115.6+ KB

In [6]:
# To know what type of data is the dataset is storing
for col in adult.columns:
    print(col,adult[col].unique())
    print("-"*50)

A1_Score ['1' '0']
--------------------------------------------------
A2_Score ['1' '0']
--------------------------------------------------
A3_Score ['1' '0']
--------------------------------------------------
A4_Score ['1' '0']
--------------------------------------------------
A5_Score ['0' '1']
--------------------------------------------------
A6_Score ['0' '1']
--------------------------------------------------
A7_Score ['1' '0']
--------------------------------------------------
A8_Score ['1' '0']
--------------------------------------------------
A9_Score ['0' '1']
--------------------------------------------------
A10_Score ['0' '1']
--------------------------------------------------
age [ 26.  24.  27.  35.  40.  36.  17.  64.  29.  33.  18.  31.  30.  34.
  38.  42.  43.  48.  37.  55.  50.  53.  20.  28.  21. 383.  47.  32.
  44.  nan  19.  58.  45.  22.  39.  25.  23.  54.  60.  41.  46.  56.
  61.  59.  52.  49.  51.]
--------------------------------------------------
gender ['f' 'm']
--------------------------------------------------
ethnicity ['White-European' 'Latino' None 'Others' 'Black' 'Asian' 'Middle Eastern '
 'Pasifika' 'South Asian' 'Hispanic' 'Turkish' 'others']
--------------------------------------------------
jundice ['no' 'yes']
--------------------------------------------------
austim ['no' 'yes']
--------------------------------------------------
contry_of_res ['United States' 'Brazil' 'Spain' 'Egypt' 'New Zealand' 'Bahamas'
 'Burundi' 'Austria' 'Argentina' 'Jordan' 'Ireland' 'United Arab Emirates'
 'Afghanistan' 'Lebanon' 'United Kingdom' 'South Africa' 'Italy'
 'Pakistan' 'Bangladesh' 'Chile' 'France' 'China' 'Australia' 'Canada'
 'Saudi Arabia' 'Netherlands' 'Romania' 'Sweden' 'Tonga' 'Oman' 'India'
 'Philippines' 'Sri Lanka' 'Sierra Leone' 'Ethiopia' 'Viet Nam' 'Iran'
 'Costa Rica' 'Germany' 'Mexico' 'Russia' 'Armenia' 'Iceland' 'Nicaragua'
 'Hong Kong' 'Japan' 'Ukraine' 'Kazakhstan' 'AmericanSamoa' 'Uruguay'
 'Serbia' 'Portugal' 'Malaysia' 'Ecuador' 'Niger' 'Belgium' 'Bolivia'
 'Aruba' 'Finland' 'Turkey' 'Nepal' 'Indonesia' 'Angola' 'Azerbaijan'
 'Iraq' 'Czech Republic' 'Cyprus']
--------------------------------------------------
used_app_before ['no' 'yes']
--------------------------------------------------
result [ 6.  5.  8.  2.  9. 10.  4.  3.  0.  1.  7.]
--------------------------------------------------
age_desc ['18 and more']
--------------------------------------------------
relation ['Self' 'Parent' None 'Health care professional' 'Relative' 'Others']
--------------------------------------------------
Class/ASD ['NO' 'YES']
--------------------------------------------------

In [7]:
adult.describe()

              age      result
count  702.000000  704.000000
mean    29.698006    4.875000
std     16.507465    2.501493
min     17.000000    0.000000
25%     21.000000    3.000000
50%     27.000000    4.000000
75%     35.000000    7.000000
max    383.000000   10.000000

In [8]:
# To know count of both 'yes' and 'no' in the target variable
adult['Class/ASD'].value_counts()

Class/ASD
NO     515
YES    189
Name: count, dtype: int64

In [9]:
# To extract all the column names
adult.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender',
       'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before',
       'result', 'age_desc', 'relation', 'Class/ASD'],
      dtype='object')